[run]
puzzle_kind = "sudoku-9x9"

[run.by_profile.ci]
puzzle_kind = "sudoku-9x9"

[PUZZLE]
name = "sudoku-9x9"
size = 9
alphabet = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

[PUZZLE.block]
rows = 3
cols = 3

[LIMITS]
solver_timeout_ms = 1000

[RENDER]
format = "pdf"
template = "classic@1"
page = "A4"
dpi = 300

[pdf]
total_puzzles = 8
pages = 2
default_target_score = 30.0
default_time_budget = 40.0

[pdf.layout]
rows = 2
cols = 2

[pdf.page]
width_cm = 29.7
height_cm = 21.0
margin_cm = 4.0
gap_cm = 2.0
footer_offset_cm = 1.0

[pdf.rendering]
font_scale_factor = 0.65

[pdf.output]
filename_prefix = "sudoku_9x9_pack"

[pdf.fallback]
seed_multiplier = 7
reduce_time_share = 0.5
min_time_budget = 2.0

[generator.full_solution]
time_limit = 1.5

[generator.reduce]
time_budget = 10.0
min_clues = 28
low_score_threshold = 10.0

[generator.minimality]
time_budget = 6.0
symmetry = "central"

[generator.interesting]
target_score = 40.0
time_budget = 20.0
single_attempt_budget = 15.0
reduce_share = 0.7
minimize_share = 0.3

[interest_scoring]
diversity_cap = 42.0
diversity_step = 6.0
richness_cap = 36.0
richness_factor = 0.55
curve_bonus_scale = 12.0
xwing_bonus = 4.0
xywing_bonus = 6.0
swordfish_bonus = 8.0
monotony_free_run = 5
monotony_penalty = 1.8
singles_share_limit = 0.65
singles_penalty_scale = 30.0
singles_score_cap = 28.0

[interest_scoring.advanced]
techniques = [
    "Naked Pairs",
    "Hidden Pairs",
    "Locked Candidates (Pointing)",
    "Locked Candidates (Claiming)",
    "X-Wing (Rows)",
    "X-Wing (Cols)",
    "XY-Wing",
    "Swordfish (Rows)",
    "Swordfish (Cols)",
]

[interest_scoring.weights]
"Naked Single" = 0.7
"Hidden Single" = 1.0
"Locked Candidates (Pointing)" = 1.6
"Locked Candidates (Claiming)" = 1.7
"Naked Pairs" = 1.9
"Hidden Pairs" = 2.1
"X-Wing (Rows)" = 3.2
"X-Wing (Cols)" = 3.2
"XY-Wing" = 3.6
"Swordfish (Rows)" = 4.0
"Swordfish (Cols)" = 4.0

[modules."sudoku-9x9".solver]
state = "default"
impl = "legacy"
sample_rate = 0.0
allow_fallback = true
contracts = "^1.0"

[modules."sudoku-9x9".solver.by_profile.ci]
state = "default"
impl = "legacy"

[modules."sudoku-9x9".solver.by_profile.dev]
state = "shadow"
impl = "novus"
sample_rate = 0.25

[modules."sudoku-9x9".generator]
state = "default"
impl = "legacy"
allow_fallback = true
contracts = "^1.0"

[modules."sudoku-9x9".generator.by_profile.ci]
state = "default"
impl = "legacy"

[modules."sudoku-9x9".printer]
state = "default"
impl = "legacy"
allow_fallback = true
contracts = "^1.0"

[modules."sudoku-9x9".printer.by_profile.ci]
state = "default"
impl = "legacy"

[modules."sudoku-9x9".difficulty]
state = "default"
impl = "baseline"
allow_fallback = true
contracts = "^1.0"

[solver.runtime]
solver_impl = "legacy"
trace_level = "none"
multitask_enabled = false
multitask_intra_solver = false
multitask_backend = "sequential"
max_workers = 1
branching_limit = 1
