name: shadow-smoke

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Run shadow smoke suite
        env:
          PYTHONPATH: src
        run: |
          pytest tests/shadow/smoke_dev.py
