name: docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'MIGRATIONS.md'
      - '.markdownlint.json'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'MIGRATIONS.md'
      - '.markdownlint.json'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            README.md
            CHANGELOG.md
            MIGRATIONS.md
            docs/**/*.md
